#
- platform: workday
  country: ZA
#
- platform: template
  sensors:
    running:
      value_template: "{{ as_timestamp(states.sensor.time.last_updated) - as_timestamp(states.sensor.uptime.state) > 60 }}"
    telegram_notifications:
      value_template: "{{ is_state('input_boolean.notification_telegram', 'on') and is_state('binary_sensor.running', 'on') }}"
    someone_home:
      value_template: "{{ is_state('group.tracked_things', 'home') or is_state('input_boolean.someone_home_forced', 'on') or is_state('input_boolean.bedtime_mode', 'on') }}"
      icon_template: "mdi:numeric-{{ states.person|selectattr('state','eq','home')|list|count}}-box-outline"
    doors_open_when_armed:
      value_template: "{{ is_state('binary_sensor.alarm_status', 'on') and (is_state('binary_sensor.door_contact_garage_double', 'on') or is_state('binary_sensor.door_contact_garage_single', 'on')) }}"
      device_class: problem
    power_warning:
      value_template: "{{ states('sensor.axpert_inv') | int < 210 }}"
      device_class: problem
    solar_below_800:
      value_template: "{{ states('sensor.axpert_pvw') | int < 800 and is_state('binary_sensor.axpert_output_source_is_grid', 'off') }}"
      delay_on: 40
    solar_below_cutoff:
      value_template: "{{ states('sensor.axpert_pvw') | int < 200 and is_state('binary_sensor.axpert_output_source_is_grid', 'off') }}"
      delay_on: 50
    poolpump_working_time:
      value_template: >
        {{ not ((state_attr('sun.sun', 'elevation') < 45 and state_attr('sun.sun', 'azimuth') > 15) and is_state_attr('sun.sun', 'rising', true)) and
        not ((state_attr('sun.sun', 'elevation') < 30 and state_attr('sun.sun', 'azimuth') < 320) and is_state_attr('sun.sun', 'rising', false)) }}
    zones_idle:
      value_template: >-
        {% set nowtimestamp = as_timestamp(states.sensor.time.last_updated) %} {{
        (nowtimestamp - as_timestamp(states.binary_sensor.door_contact_garage_double.last_changed)) >= 1800 and
        (nowtimestamp - as_timestamp(states.binary_sensor.door_contact_garage_single.last_changed)) >= 1800 and
        (nowtimestamp - as_timestamp(states.binary_sensor.paradox_zone_04.last_changed)) >= 1800 and
        (nowtimestamp - as_timestamp(states.binary_sensor.paradox_zone_15.last_changed)) >= 1800 and
        (nowtimestamp - as_timestamp(states.binary_sensor.paradox_zone_16.last_changed)) >= 1800 and
        (nowtimestamp - as_timestamp(states.binary_sensor.paradox_zone_17.last_changed)) >= 1800 }}
    axpert_output_source_is_grid:
      value_template: >-
        {{ 
          (is_state('sensor.axpert_output_source', 'Grid') and is_state('binary_sensor.power_warning', 'off')) or 
          (is_state('binary_sensor.axpert_has_solar', 'off') and is_state('sensor.axpert_battdischargea', '0')) or 
          (is_state('binary_sensor.axpert_has_solar', 'on') and is_state('sensor.axpert_battdischargea', '0') and (states('sensor.axpert_outw') | int > (states('sensor.axpert_pvw') | int - states('sensor.axpert_charge_w') | int) + 10))
        }}
    alarm_status:
      value_template: "{{ is_state('binary_sensor.paradox_output_3', 'on') }}"
      delay_on: 1
      delay_off: 1
#
################################################################################
#
- platform: mqtt
  name: axpert_status
  state_topic: "axpert/info/status"
  payload_on: "online"
  payload_off: "offline"
#
- platform: mqtt
  name: axpert_has_solar
  state_topic: "axpert/info/pigs"
  value_template: '{{ value_json.on_solar }}'
  payload_on: "1"
  payload_off: "0"
#
#- platform: mqtt
#  name: axpert_charging
#  state_topic: "axpert/info/pigs"
#  value_template: '{{ value_json.charging }}'
#  payload_on: "1"
#  payload_off: "0"
#
#- platform: mqtt
#  name: axpert_charge_ac
#  state_topic: "axpert/info/pigs"
#  value_template: '{{ value_json.charge_ac }}'
#  payload_on: "1"
#  payload_off: "0"
#
#- platform: mqtt
#  name: axpert_charge_scc
#  state_topic: "axpert/info/pigs"
#  value_template: '{{ value_json.charge_scc }}'
#  payload_on: "1"
#  payload_off: "0"
#
################################################################################
#
- platform: hikvision
  name: Garden
  host: 192.168.25.31
  username: !secret hikvision_username
  password: !secret hikvision_password
#
- platform: hikvision
  name: Driveway
  host: 192.168.25.32
  username: !secret hikvision_username
  password: !secret hikvision_password
#
################################################################################
#
- platform: mqtt
  name: door_contact_garage_double
  device_class: garage_door
  state_topic: "ha/e/s/d02-2"
  payload_on: "1"
  payload_off: "0"
#
- platform: mqtt
  name: door_contact_garage_single
  device_class: door
  state_topic: "ha/e/s/d02-1"
  payload_on: "1"
  payload_off: "0"
#
################################################################################
#
- platform: mqtt
  name: paradox_output_1
  state_topic: "ha/e/s/d05-1"
  payload_on: "1"
  payload_off: "0"
#
- platform: mqtt
  name: paradox_output_2
  state_topic: "ha/e/s/d05-2"
  payload_on: "1"
  payload_off: "0"
#
- platform: mqtt
  name: paradox_output_3
  state_topic: "ha/e/s/d05-3"
  payload_on: "1"
  payload_off: "0"
#
- platform: mqtt
  name: paradox_output_4
  state_topic: "ha/e/s/d05-4"
  payload_on: "1"
  payload_off: "0"
#
- platform: mqtt
  name: paradox_zone_01
  state_topic: "Paradox/Zone/Main Bedroom"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#
- platform: mqtt
  name: paradox_zone_04
  state_topic: "Paradox/Zone/Back Door"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: door
#
- platform: mqtt
  name: paradox_zone_05
  state_topic: "Paradox/Zone/Panic"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: opening
#
- platform: mqtt
  name: paradox_zone_14
  state_topic: "Paradox/Zone/Lounge"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#
- platform: mqtt
  name: paradox_zone_15
  state_topic: "Paradox/Zone/Garage"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#
- platform: mqtt
  name: paradox_zone_16
  state_topic: "Paradox/Zone/Front Garden"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#
- platform: mqtt
  name: paradox_zone_17
  state_topic: "Paradox/Zone/Back Alley"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#