homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 21
  unit_system: metric
  time_zone: !secret home_timezone
  customize: !include customize.yaml
  external_url: !secret http_base_url_port
  internal_url: !secret internal_url
#  whitelist_external_dirs:
#    - /tmp/hass
#
config:
#
http:
  server_port: 8443
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
#
frontend:
  themes: !include_dir_merge_named themes
#
logger:
  default: warning
#
mobile_app:
person:
sun:
system_health:
updater:
map:
media_source:
image:
#
shell_command:
  power_reading: "/etc/homeassistant/shell_scripts/sql_power.sh {{ reading }}"
  restart_paradox: 'sudo systemctl restart paradoxip'
  restart_axpert: "ssh -o StrictHostKeyChecking=no pi@192.168.25.7 'sudo systemctl restart axpert.service'"
  kodi_pip_garden: "kodi-send --host=192.168.25.10 -a 'XBMC.RunPlugin(plugin://plugin.video.surveillanceroom?action=show_preview&camera_number=1)'"
  kodi_pip_driveway: "kodi-send --host=192.168.25.10 -a 'XBMC.RunPlugin(plugin://plugin.video.surveillanceroom?action=show_preview&camera_number=2)'"
#
#########################################################################
#
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password
#
telegram_bot:
  platform: webhooks
  api_key: !secret telegram_api_key
  allowed_chat_ids:
  - !secret telegram_channel
  - !secret telegram_userid_1
  - !secret telegram_userid_2
#
shopping_list:
#
speedtestdotnet:
#
stream:
#
wake_on_lan:
#
apcupsd:
  host: 192.168.25.9
#
tts:
  platform: google_translate
  base_url: !secret internal_url
#
#weather:
#- platform: openweathermap
#  api_key: !secret openweathermap_api_key
#  mode: freedaily
#
samsungtv:
  host: 192.168.25.14
  name: lounge_samsung
  turn_on_action:
  - service: script.send_ir_04
#
proximity:
  lisp_home:
    devices:
    - device_tracker.lisp_gps
    tolerance: 50
    unit_of_measurement: m
#########################################################################
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml

light: !include lights.yaml
switch: !include switches.yaml
group: !include groups.yaml
scene: !include scenes.yaml

device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
alert: !include alert.yaml
notify: !include notify.yaml
timer: !include timer.yaml

camera: !include cameras.yaml
#media_player: !include media_players.yaml
google_assistant: !include google_assistant.yaml

recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
#