- platform: mqtt
  name: "Geyser"
  command_topic: "ha/c/r/d03-1"
  state_topic: "ha/s/r/d03-1"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "ha/s/lwt/d03"
  payload_available: "online"
  payload_not_available: "offline"
  retain: True
#
- platform: mqtt
  name: "Pool Pump"
  command_topic: "ha/c/r/d04-1"
  state_topic: "ha/s/r/d04-1"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "ha/s/lwt/d04"
  payload_available: "online"
  payload_not_available: "offline"
  retain: True
#
- platform: mqtt
  name: "Smart Plug 1"
  command_topic: "cmnd/plug1/POWER"
  state_topic: "stat/plug1/RESULT"
  value_template: "{{ value_json.POWER }}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/plug1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: True
#
- platform: mqtt
  name: "Smart Plug 2"
  command_topic: "cmnd/plug2/POWER"
  state_topic: "stat/plug2/RESULT"
  value_template: "{{ value_json.POWER }}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/plug2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: True
#